### ISSUE TITLE
VAGO -> VOGO

### ISSUE THREAD

**Issue by GDsouza** [FGMEMBERS-TERRAGIT/terraGIT#1]
The ICAO of this airport has been changed in the scenery files, but the groundnet file in this repository has not been renamed.

Unrelated topic, but Flightgear now allows a custom apt.dat file to be used. With this in mind, will one make its way into this repository?

**Comment by SH-M** [comment]
Hi Glen,
That will soon be fixed.
Right now terragit is undergoing a masssive regeneration.
http://www.thejabberwocky.net/viewtopic.php?f=51&t=854

Nice to know you are from India too (I am from Trivandrum)
If you are interested feel free to join projectIndia
http://thejabberwocky.net/viewtopic.php?f=26&t=470

**Comment by FGDATA** [comment]
yes. the Nav dat files will make it to the repo. I'll report when this is done; but it will happen once the terraGIT restructuring gets completed.

**Comment by FGDATA** [comment]
part I: completed.
https://github.com/FGMEMBERS-TERRAGIT/terraGIT/commit/18a580b08e161b24213ad031e87339c4b21f07d8

**Comment by FGDATA** [comment]
Part II: Finished with this
https://github.com/FGMEMBERS-TERRAGIT/terraGIT/commit/b08fa70968973e91b212f395bdb9d5ea824bac14

**Comment by FGDATA** [comment]
and fully renamed so fg can launch to VOGO here
https://github.com/FGMEMBERS-TERRAGIT/terraGIT/commit/94cd92f9d0941144a3676444f5345edd4f0857a9
