### ISSUE TITLE
cannot clone repository

### ISSUE THREAD

**Issue by mateusad** [FGMEMBERS-TERRAGIT/terraGIT#6]
Attempted cloning repository, but it did not work:
Cloning into 'C:\Users\mateu\Documents\GitHub\terraGIT'...
remote: Enumerating objects: 85506, done.        
remote: Counting objects: 100% (50/50), done.        
remote: Compressing objects: 100% (35/35), done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 1136 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by mateusad** [comment]
Also, I'm using Github desktop in Windows 10.

**Comment by IAHM-COL** [comment]
Hi
Using git on linux, cloning works as intended.
This is an issue with your network, or with the GitHub Desktop, not with this code

Recommendation: Try using git directly from a command window, and see if it clones

![terragit-clone](https://github.com/FGMEMBERS-TERRAGIT/terraGIT/assets/9952283/b0b37e7b-18fb-458b-a88d-b9bf24e2dd66)

Regards

**Comment by mateusad** [comment]
Tried using a command window, not worked, same error.

**Comment by IAHM-COL** [comment]
It's a large repository and you are getting trouble fetching it all
Try the options suggested here, like cloning depth 1 and then unshallow, or increasing the buffer size

https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining

Good luck

**Comment by IAHM-COL** [comment]
Now, a problem you are likely going to face is that some of the terrain tiles are significantly large, and your networks is not handling it, ie some tiles in europe are 4G+ in size. 

All those are fetched as submodules if you want them, but terraGit with no tiles is an empty scenery

**Comment by mateusad** [comment]
Using SSH I could clone the repository.

**Comment by IAHM-COL** [comment]
Good to know.
Enjoy!
